import { withRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

function Checkout({ router }) {
  let ro = useRouter();
  let co = () => {
    ro.push("/");
    toast.success("Checkout success", {
      position: "top-right",
      autoClose: 5000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "colored",
    });
  };
  useEffect(() => {
    console.log(router.query);
  }, []);
  const rupiah = (number) => {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
    }).format(number);
  };
  return (
    <div>
      <Head>
        <title>Buy !</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/log.png" />
      </Head>
      <div className="grid grid-cols-12 h-screen content-center">
        <div className="col-start-3 col-end-11 outline outline-1 row-start-2 row-end-6 grid grid-cols-12">
          <div className="bg-containt col-start-2 col-end-7">
            <Image src={router.query.imageUrl} width={500} height={500} />
          </div>
          <div className="col-start-7 col-end-12 p-[30px] flex flex-col gap-y-[50px]">
            <div className="text-[25px] font-semibold text-right">
              {router.query.name} - {router.query.brand}
            </div>
            <div className="text-right text-[30px] divide divide-y-[3px]">
              <div>Price : {rupiah(router.query.price)}</div>
              <div></div>
            </div>
            <div className="flex justify-between text-[30px]">
              <div>Total : </div>
              <div>{rupiah(router.query.price)}</div>
            </div>
            <div>
              <button
                onClick={co}
                className="w-full bg-[#00ADB5] text-white py-[5px]"
              >
                Checkout
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default withRouter(Checkout);
