import { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "@/components/navbar";
import Card from "@/components/card";

export default function Home() {
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    fetch("http://localhost:3001/products")
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/log.png" />
      </Head>
      <main>
        <Navbar />
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        {console.log(data)}
        {data
          ? data.map((product, i) => {
              return <Card product={product} key={product.id} i={i} />;
            })
          : null}
      </main>
    </>
  );
}
