import Head from "next/head";
import Navbar from "@/components/navbar";
export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/log.png" />
      </Head>
      <Navbar />
      <div className="w-screen grid grid-cols-12">
        <div className="col-start-2 col-end-12">
          <div className="text-[50px] font-semibold text-center">Dashboard</div>
          <div>
            <table className="w-full">
              <thead>
                <tr>
                  <th className="border border-[2px] border-slate-600">No</th>
                  <th>Name</th>
                  <th>Image</th>
                  <th>Brand</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>asa</td>
                  <td>asa</td>
                  <td>asa</td>
                  <td>asa</td>
                  <td>asa</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
