import Head from "next/head";
import { useState, useEffect } from "react";
import { useLoginMutation } from "@/features/apiUser";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/router";

export default function Home() {
  let [input, setInput] = useState({ username: "", password: "" });
  let [login] = useLoginMutation();
  let router = useRouter();

  useEffect(() => {
    localStorage.access_token ? router.push("/home") : null;
  }, []);

  const handleChange = (e) => {
    const value = e.target.value;
    const name = e.target.name;

    setInput({
      ...input,
      [name]: value,
    });
  };
  const submitLogin = (e) => {
    e.preventDefault();
    login(input).then((res) => {
      if (res.error) {
        toast.warn(res.error.data.message, {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "dark",
        });
      }
      if (res.data) {
        toast.success("Welcome", {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "dark",
        });
        localStorage.access_token = res.data.access_token;
        router.push("/home");
      }
    });
  };
  return (
    <>
      <Head>
        <title>Admin Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/log.png" />
      </Head>
      <ToastContainer />
      <div className="h-screen w-screen grid grid-cols-12 grid-rows-6">
        <div className="col-start-5 col-end-9 row-start-2 row-end-6 outline outline-1 outline-[#00ADB5] grid content-center grid-cols-12">
          <div className="col-start-2 col-end-12 flex flex-col gap-y-[25px]">
            <div className="text-center text-[40px] text-[#222831] font-semibold">
              Next Store
            </div>
            <div>
              <form
                onSubmit={submitLogin}
                className="flex flex-col gap-y-[20px]"
              >
                <div className="flex flex-col gap-y-[10px]">
                  <div>
                    <input
                      className="outline outline-1 outline-[#393E46]/10 focus:outline-[#393E46] p-[10px] w-full rounded-[1px]"
                      placeholder="Username"
                      type="text"
                      name="username"
                      value={input.username}
                      onChange={handleChange}
                    />
                  </div>
                  <div>
                    <input
                      className="outline outline-1 outline-[#393E46]/10 focus:outline-[#393E46] p-[10px] w-full rounded-[1px]"
                      placeholder="Password"
                      type="password"
                      onChange={handleChange}
                      name="password"
                    />
                  </div>
                </div>
                <div>
                  <button className="outline outline-1 outline-[#393E46]/10 bg-[#222831] text-white p-[10px] w-full rounded-[1px]">
                    Login
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
