import Head from "next/head";
import Navbar from "@/components/navbar";
import { useGetUsersQuery } from "@/features/apiUser";
import Trowu from "@/components/trowu";
import Link from "next/link";
import { useEffect } from "react";
import { useRouter } from "next/router";
export default function User(params) {
  let router = useRouter();
  let { data } = useGetUsersQuery({}, { refetchOnMountOrArgChange: true });
  useEffect(() => {
    !localStorage.access_token ? router.push("/") : null;
  });
  return (
    <>
      <Head>
        <title>User dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/log.png" />
      </Head>
      <Navbar />
      <div className="grid grid-cols-12">
        <div className="col-start-2 col-end-12 flex flex-col gap-y-[10px]">
          <div className="text-[50px] font-semibold text-center underline underline-offset-8 decoration-[#00ADB5]">
            List of users
          </div>
          <div className="flex flex-row-reverse">
            <button className="bg-[#00ADB5] text-white py-[5px] px-[10px] rounded">
              <Link href="/user/create">Create user</Link>
            </button>
          </div>
          <div>
            <table className="w-full table-fixed">
              <thead className="h-[30px]">
                <tr className="rounded-t border-b-2 border-[#393E46] text-[18px]">
                  <th>Name</th>
                  <th>Email</th>
                  <th>Address</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody className="gap-[5px]">
                {data
                  ? data.map((user, i) => {
                      return <Trowu user={user} key={user.id} i={i} />;
                    })
                  : null}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
